// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxpkZ6Xe4Q8Js9zLAAWWmEH68G20liaxs',
    appId: '1:591717202614:web:95792070d644add01f8417',
    messagingSenderId: '591717202614',
    projectId: 'rideit-bglr',
    authDomain: 'rideit-bglr.firebaseapp.com',
    storageBucket: 'rideit-bglr.firebasestorage.app',
    measurementId: 'G-F4W4K53KPW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-a36djkoRBS6U8llL5icmSH62VMZ7H2U',
    appId: '1:591717202614:android:7310bb00e08896c11f8417',
    messagingSenderId: '591717202614',
    projectId: 'rideit-bglr',
    storageBucket: 'rideit-bglr.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2hTbjbQX7yKCZRrmCdW8BY0VtFBYc4VM',
    appId: '1:591717202614:ios:2e129920dc49c72b1f8417',
    messagingSenderId: '591717202614',
    projectId: 'rideit-bglr',
    storageBucket: 'rideit-bglr.firebasestorage.app',
    iosBundleId: 'com.example.rideit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2hTbjbQX7yKCZRrmCdW8BY0VtFBYc4VM',
    appId: '1:591717202614:ios:2e129920dc49c72b1f8417',
    messagingSenderId: '591717202614',
    projectId: 'rideit-bglr',
    storageBucket: 'rideit-bglr.firebasestorage.app',
    iosBundleId: 'com.example.rideit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxpkZ6Xe4Q8Js9zLAAWWmEH68G20liaxs',
    appId: '1:591717202614:web:f9d4dbfd8803b4951f8417',
    messagingSenderId: '591717202614',
    projectId: 'rideit-bglr',
    authDomain: 'rideit-bglr.firebaseapp.com',
    storageBucket: 'rideit-bglr.firebasestorage.app',
    measurementId: 'G-B3M31LTN0S',
  );
}
